spring.application.name=smartinventory
spring.datasource.url=jdbc:mysql://localhost:3306/smart_inventory
spring.datasource.username=root
spring.datasource.password=324202

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/api/v1.0

aws.accessKeyId=YOUR_ACCESS_KEY_HERE
aws.secretAccessKey=YOUR_SECRET_KEY_HERE
aws.region=ap-southeast-2
aws.bucket.name=smart-inventory-earlysev7n